#!/usr/bin/env python3

import glob
import random
import sys


def get_random_wallpaper(args):
    walls = []
    for source in args:
        walls += glob.glob(source + "/*")
    print(random.choice(walls))


if __name__ == "__main__":
    args = sys.argv[1:]
    if len(args) == 0:
        raise ValueError("Please specify a path")
    get_random_wallpaper(args)


